### ISSUE TITLE
Recommended support for bower and NPM 

### ISSUE THREAD

**Issue by mishengqiang** [JoshWhite/knockoutCSSComponents#3]

**Comment by JoshWhite** [comment]
@mishengqiang I'm not sure why you would want this available with a package manager...if you are using a build tool to assemble your JS, there are probably better solutions. For example, if you're using WebPack, then [postCSS modules](https://github.com/css-modules/postcss-modules) would be a good option.

knockoutCSSComponents was intended for use with applications that don't have an integrated JS build tool.

Do you have a good use case to integrate this into the mentioned package managers?

**Comment by mishengqiang** [comment]
Bower or npm can search and install，I don't have to care about dependence. If I don't use bower or NPM, I can only solve the dependency relationship by myself.

**Comment by JoshWhite** [comment]
Sorry about the (lengthy) delay. 

I have now released this as an npm package. Bower is no longer recommended, so I haven't addressed this. 

https://www.npmjs.com/package/knockout-css-component-binding
